services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: harvester_rabbitmq
    environment:
      RABBITMQ_USER: ${RMQ_USER}
      RABBITMQ_PASSWORD: ${RMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15-alpine
    container_name: harvester_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5

  seq:
    image: datalust/seq:latest
    container_name: harvester_seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_ADMIN_PASSWORD}
    ports:
      - "5341:80"

  orchestrator:
    build:
      context: .
      dockerfile: DataHarvester.Orchestrator/Dockerfile
    container_name: harvester_orchestrator
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=${RMQ_USER}
      - RabbitMQ__Password=${RMQ_PASSWORD}
      - Seq__ServerUrl=http://seq:80
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: DataHarvester.Worker/Dockerfile
    container_name: harvester_worker
    environment:
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=${RMQ_USER}
      - RabbitMQ__Password=${RMQ_PASSWORD}
      - Seq__ServerUrl=http://seq:80
    depends_on:
      rabbitmq:
        condition: service_started