services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: harvester_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15-alpine
    container_name: harvester_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataharvester
    ports:
      - "5432:5432"

  orchestrator:
    build:
      context: .
      dockerfile: DataHarvester.Orchestrator/Dockerfile
    container_name: harvester_orchestrator
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=dataharvester;Username=postgres;Password=postgres
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - postgres
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: DataHarvester.Worker/Dockerfile
    container_name: harvester_worker
    environment:
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq